server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ /index.html; }
  location /auth  { proxy_pass http://backend:8001; }
  location /chat  { proxy_pass http://backend:8001; }
  location /stream { proxy_pass http://backend:8001; }
}
